version: "3"

services:

  todo_backend:
    container_name: todo_backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/django-app
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000

  todo_frontend:
    container_name: todo_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/node_modules/.cache
    restart: always
    command: npm start
